# Generated by Django 5.1.2 on 2024-11-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post_dislikes_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
